Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

WuKong_test:
    model: WuKong
    dataset_id: tiny_parquet
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 32
    embedding_dim: 64
    num_wukong_layers: 3
    lcb_features: 8
    fmb_features: 8
    fmb_mlp_units: [32, 32]
    fmb_mlp_activations: "relu"
    fmp_rank_k: 8
    mlp_hidden_units: [32, 32]
    mlp_hidden_activations: 'relu'
    mlp_batch_norm: True
    layer_norm: True
    net_dropout: 0
    epochs: 1
    shuffle: True
    seed: 2024
    monitor: 'AUC'
    monitor_mode: 'max'

WuKong_default: # This is a config template
    model: WuKong
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 64
    num_wukong_layers: 3
    lcb_features: 40
    fmb_features: 40
    fmb_mlp_units: [512, 256]
    fmb_mlp_activations: "relu"
    fmp_rank_k: 8
    mlp_hidden_units: [512, 256]
    mlp_hidden_activations: 'relu'
    mlp_batch_norm: True
    layer_norm: True
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: 'AUC'
    monitor_mode: 'max'
