### Tiny data for tests only
toss_ctr_v3:
    data_root: ../../data/
    data_format: parquet
    train_data: ../../data/toss_ctr_v3/train.parquet
    valid_data: ../../data/toss_ctr_v3/valid.parquet
    test_data: ../../data/toss_ctr_v3/test.parquet
