### Tiny data for tests only
toss_ctr_v1:
    data_root: ../../data/
    data_format: parquet
    train_data: ../../data/toss_ctr_v1/train.parquet
    valid_data: ../../data/toss_ctr_v1/valid.parquet
    test_data: ../../data/toss_ctr_v1/test.parquet
