name: Contributor List

on:
    pull_request:
        branches:
            - main
        types: [closed]
    workflow_dispatch:

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        steps:
            - name: Add contributor list
              uses: akhilmhdh/contributors-readme-action@master
              with:
                  readme_path: "CONTRIBUTORS.md"
                  image_size: 80
                  commit_message: "Automatically update contributors"
                  columns_per_row: 6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
