DCN_test_emb:
    batch_norm: false
    batch_size: 32
    dataset_id: tiny_emb_example8
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [64, 32]
    early_stop_patience: 2
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: null
    learning_rate: 0.0005
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_root: ./checkpoints/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
